"""changes column names to start and end

Revision ID: f220bc9361ff
Revises: 62271ca4d138
Create Date: 2023-09-27 18:53:24.726506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f220bc9361ff'
down_revision = '62271ca4d138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prep_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end', sa.DateTime(), nullable=True))
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prep_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('end')
        batch_op.drop_column('start')

    # ### end Alembic commands ###
